CREATE DATABASE WORK;
USE WORK;
CREATE TABLE EMPLOYEE(EMPNO CHAR(4),EMP_NAME VARCHAR(20),DEPT VARCHAR(20),SALARY INT,DOJ DATE NOT NULL,
BRANCH varchar(20) not null,PRIMARY KEY(EMPNO));


INSERT INTO EMPLOYEE(EMPNO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E101','AMIT','PRODUCTION',45000,'12-03-00','BANGLORE');
INSERT INTO EMPLOYEE(EMPNO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E102','AMIT','HR',70000,'03-07-02','BANGLORE');
INSERT INTO EMPLOYEE(EMPNO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E103','SUNITHA','MANAGER',120000,'11-01-01','MYSORE');
INSERT INTO EMPLOYEE(EMPNO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E105','SUNITHA','IT',67000,'01-08-01','MYSORE');
INSERT INTO EMPLOYEE(EMPNO,EMP_NAME,DEPT,SALARY,DOJ,BRANCH)VALUES('E106','MAHESH','CIVIL',145000,'20-09-03','MUMBAI');

SELECT * FROM EMPLOYEE;
SELECT EMPNO,SALARY FROM EMPLOYEE;
SELECT AVG(SALARY) FROM EMPLOYEE;
SELECT COUNT(EMP_NAME) FROM EMPLOYEE;
SELECT DISTINCT COUNT(EMPNO)FROM EMPLOYEE;
SELECT SUM(SALARY) FROM EMPLOYEE GROUP BY EMP_NAME;