CREATE DATABASE EMPLOYEE;
USE EMPLOYEE;
CREATE TABLE DEPT(DEPTNO INT,DNAME VARCHAR(20),LOC VARCHAR(20));
SELECT * FROM DEPT;
RENAME TABLE DEPT TO DEPARTMENT;

SELECT * FROM DEPARTMENT;
ALTER TABLE DEPARTMENT ADD COLUMN PINCODE INT;
ALTER TABLE DEPARTMENT CHANGE DNAME DEPT_NAME VARCHAR(20);
ALTER TABLE DEPARTMENT CHANGE COLUMN LOC LOC CHAR(10);
DROP TABLE DEPARTMENT;